### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mcmillenb** [thankso/thanksd#1]
Hi! I'm Brian, I'm [thanksd on stackoverflow](https://stackoverflow.com/users/2678454/thanksd?tab=profile) and would love to have thanksd as my github account as well. I went to go make it and coincidentally saw that you just made it yesterday. If you're not too invested, I'd love to be able to use thankds as my account. If not no worries, just thought I'd ask. -Brian

**Comment by thankso** [comment]
if this name is so important to you,tell me the reason and i will change it.

**Comment by mcmillenb** [comment]
It’s a handle I’ve had for many years and I am hoping to unify my different
dev accounts under thanksd as my singular, professional internet presence.
It’s based off of a joke I have with my friend from college, and I think of
it as a daemon of gratitude: https://kb.iu.edu/d/aiau

**Comment by mcmillenb** [comment]
Thank you very much! I do appreciate it a lot.
